#!/usr/bin/env bash
# Install this directory as a DSH bundle.
#
#   ./install.sh            # install into the "test" profile
#   ./install.sh headless   # install into another profile
#
# Three steps:
#   1. generate patch.yaml -- a bundle entry needs an absolute path, and the
#      absolute path depends on your machine, so this script writes the file
#      (patch.yaml is git-ignored, never edit it by hand);
#   2. pnpm install here (the plugin only uses types, but the editor / tsc need
#      the packages present);
#   3. dsh plugin add, which appends this package to the profile's
#      dsh.profile.bundles.
#
# This package does not write <profile>/cordis.patch.yml: the plugin has no
# config, so it needs no overlay.
#
# To undo: dsh plugin --profile <p> remove dsh-event-timeline
set -euo pipefail

PROFILE="${1:-test}"
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DST_DIR="${DSH_HOME:-$HOME/.dsh}/profiles/$PROFILE"
ENTRY="$HERE/src/index.ts"

if [ ! -d "$DST_DIR" ]; then
    echo "profile directory not found: $DST_DIR" >&2
    echo "create that profile first (see article 01), then run this script again." >&2
    exit 1
fi

echo "==> writing patch.yaml"
cat > "$HERE/patch.yaml" <<EOF
# dsh-event-timeline bundle patch: one row.
#
# This package holds a single plugin: it prints every event DSH actually
# dispatches, in order. It only listens and registers no route, so it also
# works in headless.
#
# Generated by install.sh; the entry is an absolute path. Git-ignored.
- insert:
    - id: dsh-event-timeline
      name: '$ENTRY'
EOF

if [ ! -d "$HERE/node_modules" ]; then
    echo "==> pnpm install"
    (cd "$HERE" && pnpm install)
fi

echo
echo "==> dsh plugin --profile $PROFILE add link:$HERE"
dsh plugin --profile "$PROFILE" add "link:$HERE"

cat <<ROWS

Check the composition (dsh --profile $PROFILE --dump-config):
  - id: dsh-event-timeline   prints events in dispatch order

Use it in the web UI:
  dsh --profile $PROFILE --no-open --port 3099
  # the console then shows dispatch / agent/* / session/* / tools/* lines

Or run a one-shot task (the answer goes to stdout, so do the events):
  dsh headless 'run node -e "console.log(1+1)" with the shell tool'
  # events only: dsh headless '...' 2>/dev/null | grep dsh-event-timeline
ROWS
